[project]
name = "local-dns-unbound-ansible"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
  "ansible-core>=2.17",
  "molecule>=6.0.0",
  "molecule-plugins[podman,docker]>=23.5.3",
]
